services:
  - type: web
    name: flask-totk-api-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn.config.py main:app"
    autoDeploy: false